### ISSUE TITLE
Custom field for item rendering, optional label

### ISSUE THREAD

**Issue by webmutation** [commadelimited/autoComplete.js#11]
It would be nice to allow custom rendering of list item, many webservices don't provide a properlly formatted json and the ability to change "label" to "name" or "whatever", would make this a very simple process. So by default it looks for "label" and optionally it allows other fields to be the label.

$("#textinput2").autocomplete({
                target: $('#suggestions'),
                source: jsData,
                                label:"name",
                minLength: 1
            });

**Comment by jaynathan79** [comment]
+1 this suggestion

**Comment by commadelimited** [comment]
While it's not quite what you're looking for, a recent update might offer you the functionality that you need. Version 1.4.3 adds a data-attribute to the anchor tag of each list item. This attribute contains a serialized copy of every JSON item.

https://github.com/commadelimited/autoComplete.js#data-autocomplete-attribute

Let me know if that helps you out.

**Comment by jaynathan79** [comment]
Thanks, Andy. I just went ahead and had my service return the required
format, no problem. Thanks for the quick response, though! I did raise
another issue tonight (logged as issue although I'm thinking it's my issue
rather than one with the library) around how my autocomplete lists are
rendering. The short story is that the list is rendered as a plain old
bulleted list as opposed to a styled jquery mobile list.

Any suggestions would be helpful, so thanks!

Jay
