### ISSUE TITLE
Clear ListView When Search Is Cleared

### ISSUE THREAD

**Issue by achuinard** [commadelimited/autoComplete.js#20]
I suggest this plugin should clear the listview whenever the 'x' in the search input gets clicked.

**Comment by commadelimited** [comment]
Currently there is no X in the search field. That's a good suggestion though.

**Comment by achuinard** [comment]
I made my <input type="search">, which is what I'm guessing causes the X to
appear.

On Tue, Jun 19, 2012 at 9:34 AM, Andy Matthews <
reply@reply.github.com

**Comment by neilcoplin** [comment]
Yes, the input type is what causes jQuery Mobile to put the X there.  It just means that the plugin would have to detect if it is currently a search field or not (since that is up to the person calling the plugin, not the plugin itself).  Even without the plugin support for this, you should be able to just make a click binding on the fieldset containing the input element that checks for a click of the X button.  I used the following condition in that binding, though it could probably be optimized a bit to make it work better.

```
if ($(e.target).is('span.ui-icon') || $(e.target).is('span.ui-btn-inner') || $(e.target).is('a.ui-input-clear')) {
    $('#id-of-autocomplete-widget').autocomplete('clear');
}
```

So just add your own click binding for now and you can get it to do what you want.

**Comment by commadelimited** [comment]
Ahhhh. Nice one. Lemme try that.
